//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viktorina26042022
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionSet
    {
        public int Id { get; set; }
        public string QuestionText { get; set; }
        public string Answer1 { get; set; }
        public string Answer2 { get; set; }
        public string Answer3 { get; set; }
        public string AnswerTrue { get; set; }
        public byte[] Img { get; set; }
        public Nullable<short> CountOfAnsvers { get; set; }
    }
}
